version: '3'

networks:
  experiment-network:
    driver: bridge

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
#    depends_on:
#      - sqlite3
    networks:
      - experiment-network
#  sqlite3:
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./db/:/root/db/
#    networks:
#      - experiment-network
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - experiment-network